name: Silverleaf Eldercare
favicon: null
layout_spectrum: 0.48284
typography_spectrum: 0.393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#338a97'
    - '#ffffff'
    - '#c4ddb8'
    - '#253536'
    - '#83bac1'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
