name: Silverleaf Eldercare
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43707
title: Silverleaf Eldercare - Assisted Living at Wildridge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#338a97'
    - '#ffffff'
    - '#c4ddb8'
    - '#253536'
    - '#83bac1'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
