typography_spectrum: 0.43707
color:
  brandColors:
    - '#338a97'
    - '#ffffff'
    - '#c4ddb8'
    - '#253536'
    - '#83bac1'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.35058
analytics:
  google: null
  facebook: null
  twitter: null
name: Silverleaf Eldercare
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Silverleaf Eldercare - Assisted Living at Wildridge
description: Your Golden Years Deserve A Silver Lining
purpose: []
