typography_spectrum: 0.2690122900530696
color:
  brandColors:
    - '#338a97'
    - '#ffffff'
    - '#c4ddb8'
    - '#253536'
    - '#83bac1'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.35058
analytics:
  google: null
  facebook: null
  twitter: null
name: Silverleaf Eldercare
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Welcome!
    id: 3a482dca-38f9-40b3-bab6-a0c6c1321cd5
    type: content
  - name: Our Story
    id: 88a6dea6-41cd-4b68-adb1-65b317572a42
    type: content
  - name: Take a Look Inside our Community at Wildridge
    id: 40bfddd3-8bfa-4b93-a480-b149079d97cd
    type: content
  - name: Connect With Us
    id: 4f3f7af3-3754-489f-90b2-4e7734279e66
    type: content
favicon: null
title: Silverleaf Eldercare - Assisted Living at Wildridge
description: Your Golden Years Deserve A Silver Lining
purpose: []
